### ISSUE TITLE
zip deployment failed

### ISSUE THREAD

**Issue by universooa** [MicrosoftDocs/bot-docs.ko-kr#1]
[여기에 피드백 입력]
azure에 봇 게시 하려고하는데

zip 파일은 만들어지는데 자꾸 Zip deployment failed라 하면서 실패하네요
어떡하죠!!
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [기본 봇 만들기 및 배포 자습서 - Bot Service](https://docs.microsoft.com/ko-kr/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs.ko-kr/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
안녕하세요, @universooa  님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 
 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다.
Microsoft DOCS 국제 팀
