### ISSUE TITLE
NLP 샘플을 기반으로 한다는데...

### ISSUE THREAD

**Issue by ChaeYuJin1** [MicrosoftDocs/bot-docs.ko-kr#2]
C# sample이 없어요 깃허브로 연결이 안되네요ㅠ

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [봇에 자연어 해석 추가 - Bot Service](https://docs.microsoft.com/ko-kr/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs.ko-kr/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Sub-service: **cognitive-services**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
안녕하세요. , @ChaeYuJin1 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. , @ChaeYuJin1
피드백을 주셔서 감사합니다. 
 당사의 엔지니어링 팀이 귀하의 제안 사항을 검토하고 수락했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다.
Microsoft DOCS 국제 팀
